
const dropZone   = document.getElementById('drop-zone');
const fileInput  = document.getElementById('file-upload');
const docList    = document.querySelector('.document-list');
const verifyBtn  = document.getElementById('btn-verify-documents');

// Pull the checklist generated by the triage wizard (if available)
const savedChecklist = JSON.parse(sessionStorage.getItem('civicsync_checklist') || '[]');

// Track uploaded files: { name, file, status }
let uploadedFiles = [];

// --- BUILD CHECKLIST FROM TRIAGE ---
// If the user came through the triage wizard, show their required docs
// Otherwise fall back to the static HTML items already in the list
if (savedChecklist.length > 0) {
  docList.innerHTML = '';
  savedChecklist.forEach((docName, i) => {
    const li = document.createElement('li');
    li.classList.add('doc-item');
    li.id = `doc-item-${i}`;
    li.innerHTML = `
      <div class="doc-info">
        <svg width="16" height="16" viewBox="0 0 16 16" fill="none" style="flex-shrink:0">
          <rect x="3" y="1" width="10" height="14" rx="1.5" stroke="#38bdf8" stroke-width="1.2"/>
          <path d="M5 5h6M5 8h4" stroke="#38bdf8" stroke-width="1" stroke-linecap="round"/>
        </svg>
        <span class="doc-name">${docName}</span>
      </div>
      <div class="doc-status">
        <span class="status-text status-pending">Not uploaded</span>
      </div>
    `;
    docList.appendChild(li);
  });
}

// Update static items so they start as "Not uploaded" too
document.querySelectorAll('.doc-item .status-text').forEach(el => {
  if (!el.classList.contains('status-pending')) {
    el.textContent  = 'Not uploaded';
    el.style.color  = '#cbd5e1';
    el.style.fontWeight = '500';
  }
});

// --- DRAG AND DROP ---

dropZone.addEventListener('dragover', (e) => {
  e.preventDefault();
  dropZone.classList.add('drag-active');
});

dropZone.addEventListener('dragleave', () => {
  dropZone.classList.remove('drag-active');
});

dropZone.addEventListener('drop', (e) => {
  e.preventDefault();
  dropZone.classList.remove('drag-active');
  handleFiles(Array.from(e.dataTransfer.files));
});

// Browse button / file input
fileInput.addEventListener('change', () => {
  handleFiles(Array.from(fileInput.files));
  fileInput.value = ''; // reset so same file can be re-uploaded
});

// --- FILE HANDLING ---

const ALLOWED_TYPES = ['image/jpeg', 'image/png', 'image/webp', 'application/pdf'];
const MAX_SIZE_MB   = 10;

function handleFiles(files) {
  if (!files.length) return;

  files.forEach(file => {
    // Type check
    if (!ALLOWED_TYPES.includes(file.type)) {
      showToast(`${file.name} — unsupported file type. Use JPG, PNG, or PDF.`, 'error');
      return;
    }

    // Size check
    if (file.size > MAX_SIZE_MB * 1024 * 1024) {
      showToast(`${file.name} is too large. Maximum size is ${MAX_SIZE_MB}MB.`, 'error');
      return;
    }

    // Add to tracking array
    const entry = { name: file.name, file, status: 'uploaded' };
    uploadedFiles.push(entry);

    // Try to match against a required checklist item
    const matched = matchToChecklistItem(file.name);

    if (matched !== null) {
      updateDocItemStatus(matched, 'uploaded', file.name);
    } else {
      // Add as an extra uploaded item in the list
      addExtraDocItem(file.name);
    }

    showToast(`${file.name} uploaded successfully.`, 'success');
  });

  updateVerifyButton();
}

// Simple fuzzy match: does the filename mention a keyword from the checklist item?
function matchToChecklistItem(filename) {
  const lower = filename.toLowerCase();
  const items = docList.querySelectorAll('.doc-item');

  for (let i = 0; i < items.length; i++) {
    const docName = items[i].querySelector('.doc-name').textContent.toLowerCase();
    // Match any shared significant word (4+ chars)
    const words = docName.split(/\s+/).filter(w => w.length >= 4);
    if (words.some(w => lower.includes(w))) return i;
  }
  return null;
}

function updateDocItemStatus(index, status, filename) {
  const items     = docList.querySelectorAll('.doc-item');
  const item      = items[index];
  if (!item) return;

  const statusEl  = item.querySelector('.status-text');
  const nameEl    = item.querySelector('.doc-name');

  if (status === 'uploaded') {
    statusEl.textContent = 'Uploaded';
    statusEl.style.color = '#4ade80';
    nameEl.title         = filename;
  } else if (status === 'pending') {
    statusEl.textContent = 'Verifying...';
    statusEl.style.color = '#fbbf24';
  } else if (status === 'verified') {
    statusEl.textContent = 'Verified ✓';
    statusEl.style.color = '#22c55e';
  } else if (status === 'rejected') {
    statusEl.textContent = 'Rejected';
    statusEl.style.color = '#f87171';
  }
}

function addExtraDocItem(filename) {
  const li = document.createElement('li');
  li.classList.add('doc-item', 'doc-item--extra');
  li.innerHTML = `
    <div class="doc-info">
      <svg width="16" height="16" viewBox="0 0 16 16" fill="none" style="flex-shrink:0">
        <rect x="3" y="1" width="10" height="14" rx="1.5" stroke="#38bdf8" stroke-width="1.2"/>
        <path d="M5 5h6M5 8h4" stroke="#38bdf8" stroke-width="1" stroke-linecap="round"/>
      </svg>
      <span class="doc-name" title="${filename}">${truncate(filename, 36)}</span>
    </div>
    <div class="doc-status">
      <span class="status-text" style="color:#4ade80;font-weight:600;">Uploaded</span>
    </div>
  `;
  docList.appendChild(li);
}

function truncate(str, max) {
  return str.length > max ? str.substring(0, max - 3) + '...' : str;
}

// --- VERIFY BUTTON STATE ---

function updateVerifyButton() {
  const hasFiles = uploadedFiles.length > 0;
  verifyBtn.disabled   = !hasFiles;
  verifyBtn.style.opacity = hasFiles ? '1' : '0.5';
  verifyBtn.style.cursor  = hasFiles ? 'pointer' : 'not-allowed';
}

// Start disabled
verifyBtn.disabled = true;
verifyBtn.style.opacity = '0.5';
verifyBtn.style.cursor  = 'not-allowed';

// --- VERIFY BUTTON CLICK ---

verifyBtn.addEventListener('click', () => {
  if (!uploadedFiles.length) return;

  // Show verifying state on all uploaded items
  const items = docList.querySelectorAll('.doc-item');
  items.forEach((item, i) => {
    const st = item.querySelector('.status-text');
    if (st && st.textContent === 'Uploaded') {
      updateDocItemStatus(i, 'pending');
    }
  });

  verifyBtn.disabled     = true;
  verifyBtn.innerHTML    = '<span class="btn-spinner"></span> Verifying...';

  // Simulate verification (replace with real API call)
  setTimeout(() => {
    items.forEach((item, i) => {
      const st = item.querySelector('.status-text');
      if (st && st.textContent === 'Verifying...') {
        updateDocItemStatus(i, 'verified');
      }
    });

    // Save verification result to sessionStorage
    sessionStorage.setItem('civicsync_verified', 'true');
    sessionStorage.setItem('civicsync_upload_count', uploadedFiles.length);

    verifyBtn.innerHTML = 'Verification complete ✓';
    verifyBtn.style.background = '#22c55e';

    showToast('All documents verified! Redirecting...', 'success');

    setTimeout(() => {
      window.location.href = 'verification.html';
    }, 1400);

  }, 2200);
});

// --- DRAG ACTIVE STYLE (injected since we can't edit CSS) ---
const style = document.createElement('style');
style.textContent = `
  .drag-drop-zone.drag-active {
    background: rgba(56, 189, 248, 0.08) !important;
    border-color: #38bdf8 !important;
    transform: scale(1.01);
  }
  .doc-item { transition: background 0.2s; }
  .btn-spinner {
    display: inline-block;
    width: 16px; height: 16px;
    border: 2px solid rgba(15,23,42,0.3);
    border-top-color: #0f172a;
    border-radius: 50%;
    animation: spin 0.7s linear infinite;
    vertical-align: middle;
    margin-right: 6px;
  }
  @keyframes spin { to { transform: rotate(360deg); } }
  #cs-toast {
    position: fixed; bottom: 30px; left: 50%;
    transform: translateX(-50%);
    padding: 13px 26px; border-radius: 12px;
    font-weight: 600; font-size: 0.92rem;
    z-index: 9999; box-shadow: 0 8px 24px rgba(0,0,0,0.35);
    transition: opacity 0.4s ease; white-space: nowrap;
  }
  .status-pending { color: #cbd5e1 !important; }
`;
document.head.appendChild(style);

// --- TOAST ---
function showToast(message, type = 'success') {
  const existing = document.getElementById('cs-toast');
  if (existing) existing.remove();

  const colors = {
    success: { bg: '#38bdf8', color: '#0f172a' },
    error:   { bg: '#f87171', color: '#fff'    },
  };
  const { bg, color } = colors[type] || colors.success;

  const toast = document.createElement('div');
  toast.id = 'cs-toast';
  toast.textContent = message;
  toast.style.cssText = `background:${bg}; color:${color};`;
  document.body.appendChild(toast);

  setTimeout(() => {
    toast.style.opacity = '0';
    setTimeout(() => toast.remove(), 400);
  }, 3500);
}
